# docker build -f .\DockerFile -t saft_web_java .

# Java 빌드 단계
FROM gradle:7.6.2-jdk17-focal AS build
WORKDIR /app

# 소스 코드 복사
COPY build.gradle .
COPY src ./src

# Maven을 사용하여 애플리케이션 빌드
RUN gradle build -x test

# Java 실행 단계
FROM openjdk:17-bullseye
WORKDIR /app
 
# 빌드 단계에서 생성된 JAR 파일 복사
COPY --from=build /app/build/libs/app-0.0.1-SNAPSHOT.jar .

# 애플리케이션 실행
CMD ["java", "-jar", "app-0.0.1-SNAPSHOT.jar"]